# Generated by Django 6.0.2 on 2026-02-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefiles', '0001_initial'),
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_case_number', models.CharField(max_length=20, unique=True)),
                ('court_name', models.CharField(max_length=200)),
                ('judge_name', models.CharField(blank=True, max_length=100)),
                ('hearing_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('adjourned', 'Adjourned'), ('verdict_given', 'Verdict Given'), ('closed', 'Closed')], default='scheduled', max_length=20)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('guilty', 'Guilty'), ('not_guilty', 'Not Guilty'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casefiles.casefile')),
                ('criminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='criminal.criminal')),
            ],
        ),
    ]
