# Generated by Django 6.0.2 on 2026-02-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='criminals/'),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='status',
            field=models.CharField(choices=[('wanted', 'Wanted'), ('arrested', 'Arrested'), ('convicted', 'Convicted'), ('released', 'Released')], default='wanted', max_length=15),
        ),
    ]
