# Generated by Django 6.0.2 on 2026-02-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('police', 'Police'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_number', models.CharField(max_length=20, unique=True)),
                ('rank', models.CharField(choices=[('constable', 'Constable'), ('head_constable', 'Head Constable'), ('si', 'Sub Inspector'), ('inspector', 'Inspector'), ('dsp', 'Deputy Superintendent'), ('sp', 'Superintendent'), ('dcp', 'Deputy Commissioner'), ('cp', 'Commissioner')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='active', max_length=15)),
                ('joined_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.policestation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
