# Generated by Django 6.0.2 on 2026-02-20 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefiles', '0001_initial'),
        ('fir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('evidence_type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('documentary', 'Documentary'), ('forensic', 'Forensic'), ('witness', 'Witness Statement'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location_found', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('in_lab', 'In Lab'), ('verified', 'Verified'), ('submitted', 'Submitted to Court')], default='collected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casefiles.casefile')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fir.fir')),
            ],
        ),
    ]
