# Generated by Django 6.0.2 on 2026-02-19 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criminal', '0001_initial'),
        ('fir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('closed', 'Closed'), ('dismissed', 'Dismissed')], default='open', max_length=25)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('criminals', models.ManyToManyField(blank=True, to='criminal.criminal')),
                ('fir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fir.fir')),
            ],
        ),
    ]
